### ISSUE TITLE
Support networking

### ISSUE THREAD

**Issue by bernerdschaefer** [atmanos/atmanos#9]
This will be a meta-issue for tracking the path towards a functional `net` package in the standard library.

As of Jul 24, the `net` package can be imported and compiled, but all methods are stubbed out to return errors.

The `net` package will depend on a functional Xen network device driver and some kind of TCP/IP stack.
## Device driver

Package `atman/net` implements a network device driver for Xen. It can currently be imported and used to read and write network packets, as shown in [this example](https://github.com/atmanos/example/blob/master/net/main.go).
## TCP/IP stack

Package `atman/net/ip` implements a TCP/IP stack. It currently only contains basic types for decoding network packets.

Going forward, we may incorporate [gonet](https://github.com/hsheth2/gonet) into the project for this component.

**Comment by sputnik13** [comment]
In light of the demo at gophercon, is this still open, or at least the specific things pointed out in the comment?  What are the current missing pieces in networking?

**Comment by errordeveloper** [comment]
Right now [`src/net/net_atman.go`](https://github.com/atmanos/atmanos/blob/997c34c4be19738674b3299dda59b067fab1e431/src/net/net_atman.go) is just a stub.

**Comment by errordeveloper** [comment]
Not sure if anyone feels like writing the entire TCP/IP stack from scratch in Go, so the following existing implementations may be of interest to explore:
- [picoTCP](https://github.com/tass-belgium/picotcp/wiki)
- [mirage-tcp](https://github.com/mirage/mirage-tcpip)

NetBSD TCP/IP stack would be a good fit, I am not able to find an appropriate link right now, besides from anything obvious on NetBSD itself...

Also @justincormack and @avsm might have some thoughts on this. 

I've worked with uIP and lwIP previously, but would rather recommend picoTCP over either of those, as the implementation is cleaner and is more recent etc. The authors, @danielinux and @maximevince, might be interested in this also.

**Comment by bernerdschaefer** [comment]
Thanks for the pointers, @errordeveloper!

I think, though, that we do want to build or incorporate a Go TCP/IP stack into the project. 

The goal of Atman is not _only_ to run Go programs on a hypervisor, but also to do it in Go, and leverage the things that come along with that (e.g., cross-compiling).

I think bringing in an existing TCP/IP stack would also be pretty large undertaking, because there's currently no C, cgo, or even libc in the project. 

The more promising way forward using existing tools, at the moment, is using [gonet](https://github.com/hsheth2/gonet). Some folks at GopherCon had some promising experiments combining it with Atman.

**Comment by bernerdschaefer** [comment]
@sputnik13 Good questions. I've updated the issue description to better describe the current state of things.

**Comment by danielinux** [comment]
> I think bringing in an existing TCP/IP stack would also be pretty large undertaking, because there's currently no C, cgo, or even libc in the project. 

@bernerdschaefer  just FYI, the requirements in terms of libC of a stack like picoTCP is very limited, as it's originally designed to run on bare-metal embedded applications, and the porting/cross compiling impact is very low. 

Also, at a first glance, the protocols implementation in gonet seems a bit basic/rudimental at the moment, if compared to picoTCP.

However, not crossing with external C dependencies seems a valid point in your case.

**Comment by sputnik13** [comment]
@daniellinux what protocols are you referring to in particular?

At the risk of gross oversimplification, to have full networking capabilities, the protocols required are

L2 - Ethernet, ARP, NDP
L3 - IPv4/IPv6
L4 - TCP, UDP, ICMP

All other application level protocols can then be built on top of these and there's value in providing a solid core set of protocols and requiring use of libraries for others.

Also, yes I'm taking a very narrow IP over Ethernet view here since that's what the vast majority of use cases are outside of embedded contexts.

Strictly speaking DHCP isn't required but from an "OS" standpoint, especially in the world of clouds, lacking DHCP as a core functionality makes the "OS" less usable, so it would be nice to have DHCP support built in.

Also, with respect to Ethernet, allowing VLAN support would also be really useful.

**Comment by danielinux** [comment]
@sputnik13 I am not referring to "application layer" protocols. I am talking mostly about TCP. There are many implementations out there, but I haven't seen many that offers good support for timestamps, SACKs, or with a more than mediocre congestion control mechanism. Implementing just RFC791 is not enough in 2016, while gonet seems to support just a subset of that. Moreover, it seems to have no multicast sockets, no IPv6 support, no routing and no IP layer filtering. Please note that I am not criticizing the project as whole, I reckon it's just very young. I believe it has potential to grow in the good direction especially if it can gain a few more contributors.

**Comment by sputnik13** [comment]
@danielinux thanks for the clarification.  I agree all of those are needed for a robust implementation, but I'm kind of interested in just seeing things make progress to a point where real applications can run, even if performance inhibited because congestion control algorithms are subpar, etc.

I assume that would help to drive more interest to the project and bring more people in, which in turn will lead to better implementations of things, all assuming that @bernerdschaefer wants external contributors of course.

Also, I agree keeping everything strictly go is an attractive proposition.

**Comment by bernerdschaefer** [comment]
There's been some progress on this over the past few months, and I'm ready to close this out.

I'm not sure when AtmanOS will get a fully integrated net stack, such that you could just `net.Listen` and everything works. Rather than block on this, I've moved forward with out-of-tree networking where it's easier to experiment.

[atmanos/anet](https://github.com/atmanos/anet) is now home to all the code needed to do networking under AtmanOS, with an adapter for [google/netstack](https://github.com/google/netstack) to provide the upper layers.

There's an HTTP server example in the [atmanos/example](https://github.com/atmanos/example/tree/master/netstack) repo!

**Comment by errordeveloper** [comment]
Thanks!
